/**
 * Utility functions to manipulate `Array` values.
 */

import type { Compare, Maybe, Nothing } from './domain'
import { objectKeys } from './object'
// No object imports needed anymore

/**
 * Returns the first element of an array, or `undefined` if the array is empty.
 *
 * @param arr - The input array.
 * @returns The first element of the array, or `undefined` if the array is empty.
 * @typeParam A - The type of elements in the array.
 * @public
 */
export const arrayHead = <A>(arr: A[]): Maybe<A> =>
  arr.length > 0 ? arr[0] : undefined

/**
 * Returns a new array containing all elements of the input array except for the first element.
 *
 * @param arr - The input array.
 * @returns A new array containing all elements of the input array except for the first element.
 * @public
 */
export const arrayTail = <A>(arr: A[]): A[] => arr.slice(1)

/**
 * Checks if two arrays are equal based on a custom equality function.
 *
 * @typeParam T - The type of elements in the arrays.
 * @param a - The first array.
 * @param b - The second array.
 * @param equals - The custom equality function to compare elements.
 * @returns Returns `true` if the arrays are equal, `false` otherwise.
 * @public
 */
export const areArraysEqual = <T>(
  a: T[],
  b: T[],
  equals: (a: T, b: T) => boolean
): boolean => {
  if (a.length !== b.length) return false
  else {
    for (let i = 0; i < a.length; i++) {
      if (!equals(a[i], b[i])) return false
    }
    return true
  }
}

/**
 * Checks if an array is empty.
 *
 * @param arr - The array to check.
 * @returns `true` if the array is empty, `false` otherwise.
 * @public
 */
export const isArrayEmpty = <T>(arr: T[]): arr is [] => arr.length === 0

/**
 * Checks if an array has values.
 *
 * @param arr - The array to check.
 * @returns `true` if the array has values, `false` otherwise.
 * @public
 */
export const arrayHasValues = <T>(arr: T[]): arr is [T, ...T[]] =>
  arr.length > 0

/**
 * Applies a mapping function to each element of an array and returns a new array
 * containing the mapped values, excluding any `null` or `undefined` values.
 *
 * @typeParam A - The type of the elements in the input array.
 * @typeParam B - The type of the elements in the output array.
 * @param arr - The input array.
 * @param f - The mapping function to apply to each element.
 * @returns The new array containing the mapped values.
 * @public
 */
export const filterMapArray = <A, B>(
  arr: A[],
  f: (a: A, index: number) => Maybe<B>
): B[] => {
  const buff = [] as B[]
  for (let i = 0; i < arr.length; i++) {
    const v = f(arr[i], i)
    if (v != null) {
      buff.push(v)
    }
  }
  return buff
}

/**
 * Filters out null and undefined values from an array.
 *
 * @typeParam T - The type of elements in the array.
 * @param arr - The array to filter.
 * @returns The filtered array.
 * @public
 */
export const filterNullsFromArray = <T>(arr: Array<T | Nothing>): T[] =>
  arr.filter((v): v is T => v != null)

/**
 * Compares two arrays based on their lengths and element values.
 *
 * @typeParam A - The type of elements in the arrays.
 * @param a - The first array to compare.
 * @param b - The second array to compare.
 * @param comparef - The compare function to use for comparing the elements of the arrays.
 * @param shorterFirst - Specifies whether shorter arrays should be considered smaller. Defaults to true.
 * @returns A compare function that can be used to compare arrays.
 * @public
 */
export const compareArrays = <A>(
  a: A[],
  b: A[],
  comparef: Compare<A>,
  shorterFirst = true
) => {
  if (a.length < b.length) {
    return -1 * (shorterFirst ? 1 : -1)
  } else if (a.length > b.length) {
    return 1 * (shorterFirst ? 1 : -1)
  }
  for (let i = 0; i < a.length; i++) {
    const ord = comparef(a[i], b[i])
    if (ord !== 0) return ord
  }
  return 0
}

/**
 * Generates an array of values by applying a function to each index.
 *
 * This function provides a more semantic alternative to `Array.from({ length }, (_, i) => f(i))`
 * with better readability and intent expression. It's particularly useful for creating
 * arrays with computed values based on their position.
 *
 * @example
 * ```typescript
 * // Create an array of squares
 * const squares = buildArray(5, i => i * i)
 * // Result: [0, 1, 4, 9, 16]
 *
 * // Create an array of objects with IDs
 * const items = buildArray(3, i => ({ id: i, name: `Item ${i}` }))
 * // Result: [{ id: 0, name: 'Item 0' }, { id: 1, name: 'Item 1' }, { id: 2, name: 'Item 2' }]
 * ```
 *
 * @param length - The length of the resulting array.
 * @param f - The function to apply to each index. It takes the index as a parameter and returns the corresponding value.
 * @returns An array of values generated by applying the function to each index.
 * @public
 */
export const buildArray = <A>(length: number, f: (index: number) => A): A[] =>
  Array.from({ length }, (_, i) => f(i))

/**
 * Generates an array of consecutive numbers in a specified range.
 *
 * This function provides a more intuitive API than `Array.from({ length }, (_, i) => startAt + i)`
 * for creating numeric sequences. It's commonly needed for iterations, indexing, and mathematical operations.
 *
 * @example
 * ```typescript
 * // Create a range from 0 to 4
 * const zeroToFour = range(5)
 * // Result: [0, 1, 2, 3, 4]
 *
 * // Create a range from 10 to 14
 * const tenToFourteen = range(5, 10)
 * // Result: [10, 11, 12, 13, 14]
 *
 * // Use for creating test data
 * const testIds = range(100, 1000)
 * // Result: [1000, 1001, 1002, ..., 1099]
 * ```
 *
 * @param length - The length of the array to generate.
 * @param startAt - The starting value of the range. Default is 0.
 * @returns An array of numbers in the specified range.
 * @public
 */
export const range = (length: number, startAt = 0): number[] =>
  Array.from({ length }, (_, i) => startAt + i)

/**
 * Creates a new array with the specified length and fills it with the provided value.
 *
 * This function provides a more semantic alternative to `Array(length).fill(value)` or
 * `new Array(length).fill(value)` with better type inference and clearer intent.
 * It's particularly useful when you need arrays of non-primitive values or when
 * working with functional programming patterns.
 *
 * @example
 * ```typescript
 * // Create an array of default objects
 * const defaultUsers = fillArray(3, { name: '', active: false })
 * // Result: [{ name: '', active: false }, { name: '', active: false }, { name: '', active: false }]
 *
 * // Create an array of empty arrays
 * const matrix = fillArray(3, [] as number[])
 * // Result: [[], [], []]
 *
 * // Create an array of functions
 * const handlers = fillArray(5, () => console.log('handler'))
 * // Result: [function, function, function, function, function]
 * ```
 *
 * @typeParam A - The type of the elements in the array.
 * @param length - The length of the new array.
 * @param value - The value to fill the array with.
 * @returns A new array filled with the specified value.
 * @public
 */
export const fillArray = <A>(length: number, value: A): A[] =>
  buildArray(length, () => value)

/**
 * Removes duplicate objects from an array based on a key extraction function.
 *
 * This function removes duplicates from arrays of objects by extracting a primitive
 * key from each object and using that key to determine uniqueness. When duplicates
 * are found, the first occurrence is kept.
 *
 * @example
 * ```typescript
 * // Remove users with duplicate IDs
 * const users = [
 *   { id: 1, name: 'Alice' },
 *   { id: 2, name: 'Bob' },
 *   { id: 1, name: 'Alice Clone' },
 *   { id: 3, name: 'Charlie' }
 * ]
 * const uniqueUsers = uniqueByPrimitive(users, user => user.id)
 * // Result: [
 * //   { id: 1, name: 'Alice' },
 * //   { id: 2, name: 'Bob' },
 * //   { id: 3, name: 'Charlie' }
 * // ]
 * ```
 *
 * @example
 * ```typescript
 * // Remove products with duplicate names
 * const products = [
 *   { name: 'Laptop', price: 1000 },
 *   { name: 'Mouse', price: 25 },
 *   { name: 'Laptop', price: 1200 },
 *   { name: 'Keyboard', price: 75 }
 * ]
 * const uniqueProducts = uniqueByPrimitive(products, p => p.name)
 * // Result: [
 * //   { name: 'Laptop', price: 1000 },
 * //   { name: 'Mouse', price: 25 },
 * //   { name: 'Keyboard', price: 75 }
 * // ]
 * ```
 *
 * @example
 * ```typescript
 * // Use with complex key extraction
 * const events = [
 *   { date: '2023-01-01', type: 'click' },
 *   { date: '2023-01-01', type: 'hover' },
 *   { date: '2023-01-01', type: 'click' },
 *   { date: '2023-01-02', type: 'click' }
 * ]
 * const uniqueEvents = uniqueByPrimitive(events, e => `${e.date}-${e.type}`)
 * // Result: [
 * //   { date: '2023-01-01', type: 'click' },
 * //   { date: '2023-01-01', type: 'hover' },
 * //   { date: '2023-01-02', type: 'click' }
 * // ]
 * ```
 *
 * @typeParam T - The type of elements in the input array
 * @param values - The input array containing objects to deduplicate
 * @param predicate - Function that extracts a primitive key from each element for comparison
 * @returns A new array with duplicate elements removed based on the extracted key
 * @public
 */
export const uniqueByPrimitive = <T>(
  values: T[],
  predicate: (a: T) => string | number | symbol
): T[] => {
  const map: Record<string | number | symbol, T> = {}
  values.forEach(v => {
    map[predicate(v)] = v
  })
  return objectKeys(map).map(k => map[k])
}

/**
 * Removes the first occurrence of an item from an array.
 *
 * @typeParam A - The type of the array elements.
 * @param arr - The array from which to remove the item.
 * @param item - The item to remove from the array.
 * @returns `true` if the item was found and removed, `false` otherwise.
 * @public
 */
export const removeOneFromArray = <A>(arr: A[], item: A): boolean => {
  const index = arr.indexOf(item)
  if (index < 0) {
    return false
  } else {
    arr.splice(index, 1)
    return true
  }
}

/**
 * Removes all occurrences of an item from an array.
 *
 * @typeParam A - The type of the array elements.
 * @param arr - The array from which to remove the item.
 * @param item - The item to remove from the array.
 * @returns `true` if at least one occurrence was found and removed, `false` otherwise.
 * @public
 */
export const removeAllFromArray = <A>(arr: A[], item: A): boolean => {
  let removed = false
  while (removeOneFromArray(arr, item)) {
    removed = true
  }
  return removed
}

/**
 * Removes the first occurrence in an array that satisfy the given predicate.
 *
 * @typeParam A - The type of elements in the array.
 * @param arr - The array from which elements will be removed.
 * @param predicate - The predicate function used to determine which elements to remove.
 * @returns `true` if at least one element was removed, `false` otherwise.
 * @public
 */
export const removeOneFromArrayByPredicate = <A>(
  arr: A[],
  predicate: (a: A) => boolean
): boolean => {
  const index = arr.findIndex(predicate)
  if (index < 0) {
    return false
  } else {
    arr.splice(index, 1)
    return true
  }
}

/**
 * Removes all occurrences in an array that satisfy the given predicate.
 *
 * @typeParam A - The type of elements in the array.
 * @param arr - The array from which elements will be removed.
 * @param predicate - The predicate function used to determine which elements to remove.
 * @returns `true` if at least one element was removed, `false` otherwise.
 * @public
 */
export const removeAllFromArrayByPredicate = <A>(
  arr: A[],
  predicate: (a: A) => boolean
): boolean => {
  let removed = false
  while (removeOneFromArrayByPredicate(arr, predicate)) {
    removed = true
  }
  return removed
}

/**
 * Represents the different operations that can be performed on an array.
 *
 * @public
 */
export type ArrayDiffOperations<T> = {
  removals: Array<{ at: number; qt: number }>
  swaps: Array<{ from: number; to: number }>
  inserts: Array<{ at: number; values: T[] }>
}

/**
 * Calculates the difference operations between two arrays based on a key function.
 *
 * @typeParam T - The type of elements in the arrays.
 * @typeParam K - The type of the key used to compare elements.
 * @param from - The source array.
 * @param to - The target array.
 * @param getKey - The key function used to compare elements.
 * @returns The difference operations between the two arrays.
 * @public
 */
export const arrayDiffOperations = <T, K>(
  from: T[],
  to: T[],
  getKey: (v: T) => K
): ArrayDiffOperations<T> => {
  const ops: ArrayDiffOperations<T> = {
    removals: [],
    swaps: [],
    inserts: [],
  }
  const { removals, inserts, swaps } = ops
  const mapB = new Map<K, number>()
  to.forEach((v, i) => mapB.set(getKey(v), i))

  const indexesOfAThatDoNotExistInB = from
    .map((v, i) => [v, i] as const)
    .filter(([v]) => !mapB.has(getKey(v)))
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    .map(([_, i]) => i)
  for (let i = indexesOfAThatDoNotExistInB.length - 1; i >= 0; i--) {
    const p = indexesOfAThatDoNotExistInB[i]
    const last = removals.length > 0 ? removals[removals.length - 1] : undefined
    if (last != null && last.at === p + 1) {
      last.at--
      last.qt++
    } else {
      removals.push({ at: p, qt: 1 })
    }
  }

  const mapA = new Map<K, number>()
  from.forEach((v, i) => mapA.set(getKey(v), i))

  const indexesOfBThatDoNotExistInA = to
    .map((v, i) => [v, i] as const)
    .filter(([v]) => !mapA.has(getKey(v)))
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    .map(([_, i]) => i)
  for (const p of indexesOfBThatDoNotExistInA) {
    const last = inserts.length > 0 ? inserts[inserts.length - 1] : undefined
    if (last != null && last.at + last.values.length === p) {
      last.values.push(to[p])
    } else {
      inserts.push({ at: p, values: [to[p]] })
    }
  }

  const ra = from.filter((_, i) => !indexesOfAThatDoNotExistInB.includes(i))
  const mapRA = new Map<K, number>()
  for (let i = 0; i < ra.length; i++) {
    mapRA.set(getKey(ra[i]), i)
  }

  const rb = to.filter((_, i) => !indexesOfBThatDoNotExistInA.includes(i))
  for (let i = 0; i < rb.length; i++) {
    const bk = getKey(rb[i])

    const ai = mapRA.get(bk)!
    if (ai == null || i === ai) continue
    const ak = getKey(ra[i])
    mapRA.delete(ak)
    swaps.push({ from: i, to: ai })
  }
  return ops
}

/**
 * Applies a series of operations to an array and returns the modified array.
 *
 * @typeParam T - The type of elements in the array.
 * @param operations - The operations to apply.
 * @param start - The initial array.
 * @returns The modified array after applying the operations.
 * @public
 */
export const applyArrayDiffOperations = <T>(
  operations: ArrayDiffOperations<T>,
  start: T[]
): T[] => {
  const buff = [...start]
  for (const { at, qt } of operations.removals) {
    buff.splice(at, qt)
  }
  for (const { from, to } of operations.swaps) {
    const t = buff[to]
    buff[to] = buff[from]
    buff[from] = t
  }
  for (const op of operations.inserts) {
    buff.splice(op.at, 0, ...op.values)
  }
  return buff
}

/**
 * Joins an array of values into a string using a conjunction and separator.
 *
 * @param arr - The array of values to join.
 * @param conjunction - The conjunction to use between the second-to-last and last value. Default is ' and '.
 * @param separator - The separator to use between each value. Default is ', '.
 * @returns The joined string.
 * @public
 */
export const joinArrayWithConjunction = <A>(
  arr: A[],
  conjunction = ' and ',
  separator = ', '
): string => {
  if (arr.length === 0) return ''
  if (arr.length === 1) return String(arr[0])
  return `${arr.slice(0, -1).join(separator)}${conjunction}${String(arr[arr.length - 1])}`
}

/**
 * Assigns ranks to the elements in the array based on the provided compare function.
 * The ranks are assigned in ascending order, with the lowest value receiving a rank of 0.
 * If there are duplicate values, the rank of the duplicates can be incremented or not based on the `incrementDuplicates` parameter.
 *
 * @typeParam T - The type of elements in the array.
 * @param array - The array to rank.
 * @param compare - The compare function used to determine the order of elements.
 * @param incrementDuplicates - Whether to increment the rank of duplicate values.
 * @returns An array of ranks corresponding to the elements in the input array.
 * @public
 */
export const rankArray = <T>(
  array: T[],
  compare: (a: T, b: T) => number,
  incrementDuplicates: boolean = true
): number[] => {
  const arr = array.map((v, i): [T, number] => [v, i])
  arr.sort((a, b) => compare(a[0], b[0]))
  const ranks = new Array<number>(arr.length)
  let rank = 0
  let last = arr[0][0]
  for (let i = 0; i < arr.length; i++) {
    const [v, index] = arr[i]
    if (compare(v, last) !== 0) {
      rank = i
      last = v
    }
    ranks[index] = rank
    if (incrementDuplicates) rank++
  }
  return ranks
}

/**
 * Splits an array into chunks of the specified size.
 *
 * This function divides an array into smaller arrays of a fixed size.
 * The last chunk may contain fewer elements if the array length is not
 * evenly divisible by the chunk size.
 *
 * @example
 * ```typescript
 * const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
 * const chunks = chunk(numbers, 3)
 * // Result: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
 *
 * const uneven = chunk([1, 2, 3, 4, 5], 2)
 * // Result: [[1, 2], [3, 4], [5]]
 * ```
 *
 * @param array - The array to chunk
 * @param size - The size of each chunk (must be positive)
 * @returns An array of chunks
 * @public
 */
export const chunk = <T>(array: readonly T[], size: number): T[][] => {
  if (size <= 0) {
    throw new Error('Chunk size must be positive')
  }

  const result: T[][] = []
  for (let i = 0; i < array.length; i += size) {
    result.push(array.slice(i, i + size))
  }
  return result
}

/**
 * Partitions an array into two arrays based on a predicate.
 *
 * This function splits an array into two parts: elements that satisfy
 * the predicate and elements that don't. The order of elements is preserved.
 *
 * @example
 * ```typescript
 * const numbers = [1, 2, 3, 4, 5, 6]
 * const [evens, odds] = partition(numbers, n => n % 2 === 0)
 * // evens: [2, 4, 6]
 * // odds: [1, 3, 5]
 * ```
 *
 * @param array - The array to partition
 * @param predicate - Function that tests each element
 * @returns A tuple containing [matching elements, non-matching elements]
 * @public
 */
export const partition = <T>(
  array: readonly T[],
  predicate: (item: T) => boolean
): [T[], T[]] => {
  const truthy: T[] = []
  const falsy: T[] = []

  for (const item of array) {
    if (predicate(item)) {
      truthy.push(item)
    } else {
      falsy.push(item)
    }
  }

  return [truthy, falsy]
}

/**
 * Groups array elements by a key function.
 *
 * This function creates an object where keys are the result of the key function
 * and values are arrays of elements that produced that key.
 *
 * @example
 * ```typescript
 * const users = [
 *   { name: 'Alice', department: 'Engineering' },
 *   { name: 'Bob', department: 'Engineering' },
 *   { name: 'Carol', department: 'Marketing' }
 * ]
 * const byDepartment = groupBy(users, user => user.department)
 * // Result: {
 * //   Engineering: [{ name: 'Alice', ... }, { name: 'Bob', ... }],
 * //   Marketing: [{ name: 'Carol', ... }]
 * // }
 * ```
 *
 * @param array - The array to group
 * @param keyFn - Function that extracts the grouping key from each element
 * @returns An object with grouped elements
 * @public
 */
export const groupBy = <T, K extends string | number | symbol>(
  array: readonly T[],
  keyFn: (item: T) => K
): Record<K, T[]> => {
  const result = {} as Record<K, T[]>

  for (const item of array) {
    const key = keyFn(item)
    if (result[key]) {
      result[key].push(item)
    } else {
      result[key] = [item]
    }
  }

  return result
}
