/**
 * Represents a mapping of HTML event names to their corresponding event types.
 *
 * @public
 */
export type HTMLEvents = {
  abort: Event
  afterprint: Event
  animationcancel: AnimationEvent
  animationend: AnimationEvent
  animationiteration: AnimationEvent
  animationstart: AnimationEvent
  auxclick: MouseEvent
  beforeinput: InputEvent
  beforeprint: Event
  beforeunload: BeforeUnloadEvent
  blur: FocusEvent
  cancel: Event
  canplay: Event
  canplaythrough: Event
  change: Event
  click: MouseEvent
  close: Event
  compositionend: CompositionEvent
  compositionstart: CompositionEvent
  compositionupdate: CompositionEvent
  contextmenu: MouseEvent
  copy: ClipboardEvent
  cuechange: Event
  cut: ClipboardEvent
  dblclick: MouseEvent
  drag: DragEvent
  dragend: DragEvent
  dragenter: DragEvent
  dragexit: Event
  dragleave: DragEvent
  dragover: DragEvent
  dragstart: DragEvent
  drop: DragEvent
  durationchange: Event
  emptied: Event
  ended: Event
  error: ErrorEvent
  focus: FocusEvent
  focusin: FocusEvent
  focusout: FocusEvent
  formdata: FormDataEvent
  fullscreenchange: Event
  fullscreenerror: Event
  gotpointercapture: PointerEvent
  hashchange: HashChangeEvent
  input: Event
  invalid: Event
  keydown: KeyboardEvent
  keypress: KeyboardEvent
  keyup: KeyboardEvent
  languagechange: Event
  load: Event
  loadeddata: Event
  loadedmetadata: Event
  loadend: ProgressEvent
  loadstart: ProgressEvent
  lostpointercapture: PointerEvent
  message: MessageEvent
  messageerror: MessageEvent
  mousedown: MouseEvent
  mouseenter: MouseEvent
  mouseleave: MouseEvent
  mousemove: MouseEvent
  mouseout: MouseEvent
  mouseover: MouseEvent
  mouseup: MouseEvent
  offline: Event
  online: Event
  orientationchange: Event
  pagehide: PageTransitionEvent
  pageshow: PageTransitionEvent
  paste: ClipboardEvent
  pause: Event
  play: Event
  playing: Event
  pointercancel: PointerEvent
  pointerdown: PointerEvent
  pointerenter: PointerEvent
  pointerleave: PointerEvent
  pointerlockchange: Event
  pointerlockerror: Event
  pointermove: PointerEvent
  pointerout: PointerEvent
  pointerover: PointerEvent
  pointerrawupdate: PointerEvent
  pointerup: PointerEvent
  popstate: PopStateEvent
  progress: ProgressEvent
  ratechange: Event
  readystatechange: Event
  rejectionhandled: PromiseRejectionEvent
  reset: Event
  resize: UIEvent
  scroll: Event
  scrollend: Event
  securitypolicyviolation: SecurityPolicyViolationEvent
  seeked: Event
  seeking: Event
  select: Event
  selectionchange: Event
  selectstart: Event
  slotchange: Event
  stalled: Event
  storage: StorageEvent
  submit: SubmitEvent
  suspend: Event
  timeupdate: Event
  toggle: Event
  touchcancel: TouchEvent
  touchend: TouchEvent
  touchmove: TouchEvent
  touchstart: TouchEvent
  transitioncancel: TransitionEvent
  transitionend: TransitionEvent
  transitionrun: TransitionEvent
  transitionstart: TransitionEvent
  unhandledrejection: PromiseRejectionEvent
  unload: Event
  visibilitychange: Event
  volumechange: Event
  waiting: Event
  wheel: WheelEvent
}
