export type SVGAttributes = {
  accentHeight: number
  accumulate: 'none' | 'sum'
  additive: 'replace' | 'sum'
  alignmentBaseline:
    | 'auto'
    | 'baseline'
    | 'before-edge'
    | 'text-before-edge'
    | 'middle'
    | 'central'
    | 'after-edge'
    | 'text-after-edge'
    | 'ideographic'
    | 'alphabetic'
    | 'hanging'
    | 'mathematical'
    | 'inherit'
  allowReorder: 'no' | 'yes'
  alphabetic: number
  amplitude: number
  arabicForm: 'initial' | 'medial' | 'terminal' | 'isolated'
  ascent: number
  attributeName: string
  attributeType: string
  autoReverse: 'true' | 'false'
  azimuth: number
  baseFrequency: number
  baseProfile: string
  baselineShift: number
  bbox: number
  begin: number
  bias: number
  by: number
  calcMode: string
  capHeight: number
  clip: number
  clipPath: string
  clipPathUnits: string
  clipRule: string
  colorInterpolation: string
  colorInterpolationFilters: 'auto' | 'sRGB' | 'linearRGB' | 'inherit'
  colorProfile: string
  colorRendering: string
  contentScriptType: string
  contentStyleType: string
  cursor: string
  cx: number
  cy: number
  d: string
  decelerate: number
  descent: number
  diffuseConstant: number
  direction: string
  display: string
  divisor: number
  dominantBaseline: string
  dur: number
  dx: number
  dy: number
  edgeMode: string
  elevation: number
  enableBackground: string
  end: number
  exponent: number
  externalResourcesRequired: 'true' | 'false'
  fill: string
  fillOpacity: number
  fillRule: string
  filter: string
  filterRes: number
  filterUnits: string
  floodColor: string
  floodOpacity: number
  focusable: 'true' | 'false' | 'auto'
  fontFamily: string
  fontSize: number
  fontSizeAdjust: number
  fontStretch: string
  fontStyle: string
  fontVariant: string
  fontWeight: string
  format: string
  from: number
  fx: number
  fy: number
  g1: number
  g2: number
  glyphName: string
  glyphOrientationHorizontal: number
  glyphOrientationVertical: number
  glyphRef: string
  gradientTransform: string
  gradientUnits: string
  hanging: number
  height: number
  horizAdvX: number
  horizOriginX: number
  ideographic: number
  imageRendering: string
  in: string
  in2: string
  intercept: number
  k: number
  k1: number
  k2: number
  k3: number
  k4: number
  kernelMatrix: string
  kernelUnitLength: number
  kerning: number
  keyPoints: string
  keySplines: string
  keyTimes: string
  lengthAdjust: string
  letterSpacing: number
  lightingColor: string
  limitingConeAngle: number
  local: number
  markerEnd: string
  markerHeight: number
  markerMid: string
  markerStart: string
  markerUnits: string
  markerWidth: number
  mask: string
  maskContentUnits: string
  maskUnits: string
  mathematical: number
  mode: string
  numOctaves: number
  offset: number
  opacity: number
  operator: string
  order: number
  orient: string
  orientation: number
  origin: number
  overflow: string
  overlinePosition: number
  overlineThickness: number
  paintOrder: string
  panose1: number
  pathLength: number
  patternContentUnits: string
  patternTransform: string
  patternUnits: string
  pointerEvents: string
  points: string
  pointsAtX: number
  pointsAtY: number
  pointsAtZ: number
  preserveAlpha: 'true' | 'false'
  preserveAspectRatio: string
  primitiveUnits: string
  r: number
  radius: number
  refX: number
  refY: number
  renderingIntent: string
  repeatCount: number
  repeatDur: number
  requiredExtensions: string
  requiredFeatures: string
  restart: string
  result: string
  rotate: number
  rx: number
  ry: number
  scale: number
  seed: number
  shapeRendering: string
  slope: number
  spacing: number
  specularConstant: number
  specularExponent: number
  speed: number
  spreadMethod: string
  startOffset: number
  stdDeviation: number
  stemh: number
  stemv: number
  stitchTiles: string
  stopColor: string
  stopOpacity: number
  strikethroughPosition: number
  strikethroughThickness: number
  string: string
  stroke: string
  strokeDasharray: string
  strokeDashoffset: number
  strokeLinecap: string
  strokeLinejoin: string
  strokeMiterlimit: number
  strokeOpacity: number
  strokeWidth: number
  surfaceScale: number
  systemLanguage: string
  tableValues: string
  targetX: number
  targetY: number
  textAnchor: string
  textDecoration: string
  textLength: number
  textRendering: string
  to: number
  transform: string
  u1: number
  u2: number
  underlinePosition: number
  underlineThickness: number
  unicode: number
  unicodeBidi: string
  unicodeRange: string
  unitsPerEm: number
  vAlphabetic: number
  values: string
  vectorEffect: string
  version: string
  vertAdvY: number
  vertOriginX: number
  vertOriginY: number
  vHanging: number
  vIdeographic: number
  viewBox: string
  viewTarget: number
  visibility: string
  vMathematical: number
  width: number
  widths: number
  wordSpacing: number
  writingMode: string
  x1: number
  x2: number
  x: number
  xChannelSelector: string
  xHeight: number
  xlinkActuate: string
  xlinkArcrole: string
  xlinkHref: string
  xlinkRole: string
  xlinkShow: string
  xlinkTitle: string
  xlinkType: string
  xmlBase: string
  xmlLang: string
  xmlns: string
  xmlnsXlink: string
  xmlSpace: string
  y1: number
  y2: number
  y: number
  yChannelSelector: string
  z: number
  zoomAndPan: string
}
