/**
 * Represents the attributes that can be used in SVG elements.
 *
 * @public
 */
export type SVGAttributes = {
  'accent-height': number
  accumulate: 'none' | 'sum'
  additive: 'replace' | 'sum'
  'alignment-baseline':
    | 'auto'
    | 'baseline'
    | 'before-edge'
    | 'text-before-edge'
    | 'middle'
    | 'central'
    | 'after-edge'
    | 'text-after-edge'
    | 'ideographic'
    | 'alphabetic'
    | 'hanging'
    | 'mathematical'
    | 'inherit'
  'allow-reorder': 'no' | 'yes'
  alphabetic: number
  amplitude: number
  'arabic-form': 'initial' | 'medial' | 'terminal' | 'isolated'
  ascent: number
  attributeName: string
  attributeType: string
  autoReverse: 'true' | 'false'
  azimuth: number
  baseFrequency: number
  baseProfile: string
  'baseline-shift': number
  bbox: number
  begin: number
  bias: number
  by: number
  calcMode: string
  'cap-height': number
  clip: number
  'clip-path': string
  clipPathUnits: string
  clipRule: string
  'color-interpolation': string
  'color-interpolation-filters': 'auto' | 'sRGB' | 'linearRGB' | 'inherit'
  colorProfile: string
  'color-rendering': string
  contentScriptType: string
  contentStyleType: string
  cursor: string
  cx: number
  cy: number
  d: string
  decelerate: number
  descent: number
  diffuseConstant: number
  direction: string
  display: string
  divisor: number
  'dominant-baseline': string
  dur: number
  dx: number
  dy: number
  edgeMode: string
  elevation: number
  enableBackground: string
  end: number
  exponent: number
  externalResourcesRequired: 'true' | 'false'
  fill: string
  'fill-opacity': number
  'fill-rule': string
  filter: string
  filterRes: number
  filterUnits: string
  'flood-color': string
  'flood-opacity': number
  focusable: 'true' | 'false' | 'auto'
  'font-family': string
  'font-size': number
  'font-size-adjust': number
  'font-stretch': string
  'font-style': string
  'font-variant': string
  'font-weight': string
  format: string
  from: number
  fx: number
  fy: number
  g1: number
  g2: number
  'glyph-name': string
  'glyph-orientation-horizontal': number
  'glyph-orientation-vertical': number
  glyphRef: string
  gradientTransform: string
  gradientUnits: string
  hanging: number
  height: number
  'horiz-adv-x': number
  'horiz-origin-x': number
  'horiz-origin-y': number
  ideographic: number
  'image-rendering': string
  in: string
  in2: string
  intercept: number
  k: number
  k1: number
  k2: number
  k3: number
  k4: number
  kernelMatrix: string
  kernelUnitLength: number
  kerning: number
  keyPoints: string
  keySplines: string
  keyTimes: string
  lengthAdjust: string
  'letter-spacing': number
  'lighting-color': string
  limitingConeAngle: number
  local: number
  'marker-end': string
  markerHeight: number
  'marker-mid': string
  'marker-start': string
  markerUnits: string
  markerWidth: number
  mask: string
  maskContentUnits: string
  maskUnits: string
  mathematical: number
  mode: string
  numOctaves: number
  offset: number
  opacity: number
  operator: string
  order: number
  orient: string
  orientation: number
  origin: number
  overflow: string
  'overline-position': number
  'overline-thickness': number
  'paint-order': string
  'panose-1': number
  pathLength: number
  patternContentUnits: string
  patternTransform: string
  patternUnits: string
  'pointer-events': string
  points: string
  pointsAtX: number
  pointsAtY: number
  pointsAtZ: number
  preserveAlpha: 'true' | 'false'
  preserveAspectRatio: string
  primitiveUnits: string
  r: number
  radius: number
  refX: number
  refY: number
  'rendering-intent': string
  repeatCount: number
  repeatDur: number
  requiredExtensions: string
  requiredFeatures: string
  restart: string
  result: string
  rotate: number
  rx: number
  ry: number
  scale: number
  seed: number
  'shape-rendering': string
  slope: number
  spacing: number
  specularConstant: number
  specularExponent: number
  speed: number
  spreadMethod: string
  startOffset: number
  stdDeviation: number
  stemh: number
  stemv: number
  stitchTiles: string
  'stop-color': string
  'stop-opacity': number
  'strikethrough-position': number
  'strikethrough-thickness': number
  string: string
  stroke: string
  'stroke-dasharray': string
  'stroke-dashoffset': number
  'stroke-linecap': string
  'stroke-linejoin': string
  'stroke-miterlimit': number
  'stroke-opacity': number
  'stroke-width': number
  surfaceScale: number
  systemLanguage: string
  tableValues: string
  targetX: number
  targetY: number
  'text-anchor': string
  'text-decoration': string
  textLength: number
  'text-rendering': string
  to: number
  transform: string
  'transform-origin': string
  u1: number
  u2: number
  'underline-position': number
  'underline-thickness': number
  unicode: number
  'unicode-bidi': string
  'unicode-range': string
  'units-per-em': number
  'v-alphabetic': number
  values: string
  'vector-effect': string
  version: string
  'vert-adv-y': number
  'vert-origin-x': number
  'vert-origin-y': number
  'v-hanging': number
  'v-ideographic': number
  viewBox: string
  viewTarget: number
  visibility: string
  'v-mathematical': number
  width: number
  widths: number
  'word-spacing': number
  'writing-mode': string
  x1: number
  x2: number
  x: number
  xChannelSelector: string
  'x-height': number
  xlinkActuate: string
  xlinkArcrole: string
  xlinkHref: string
  xlinkRole: string
  xlinkShow: string
  xlinkTitle: string
  xlinkType: string
  xmlBase: string
  xmlLang: string
  xmlns: string
  xmlnsXlink: string
  xmlSpace: string
  y1: number
  y2: number
  y: number
  yChannelSelector: string
  z: number
  zoomAndPan: string
}
