name: Publish Docs

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Yarn Install
        run: yarn install
      - name: Build Demos
        run: yarn build:demos
      - name: Assemble Docs
        run: yarn docs
      - name: Build Docs
        run: yarn build --filter=@tempos/docs
      - name: Build Pages
        working-directory: apps/docs
        run: yarn docs:static
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'apps/docs/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
