name: Publish Docs

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: PNPM Install
        run: pnpm install
      - name: Build Dependencies
        run: pnpm run build --filter="@tempots/std" --filter="@tempots/dom"
      - name: Build Demos
        run: pnpm run build:demos
      - name: Assemble Docs
        run: pnpm run docs
      - name: Build Docs
        run: pnpm run build --filter=@tempos/docs
      - name: Build Pages
        working-directory: apps/docs
        run: pnpm run docs:static
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'apps/docs/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
